name: Build and test

on: [push, pull_request]

jobs:
  linux:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1
    - name: Configure
      run: bash configure
    - name: Build
      run: make images
    - name: Verify
      run: ./build/*/images/jdk/bin/java -version

