name: Build and test

on: [push, pull_request]

jobs:
  build_linux_x86_64_release:
    name: Build Linux x86_64 Release
    runs-on: 'ubuntu-latest'
    env: 
      BOOT_JDK_VERSION: '14.0.2'
      BOOT_JDK_FILENAME: 'openjdk-14.0.2_linux-x64_bin.tar.gz'
      BOOT_JDK_URL: 'https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz'
      BOOT_JDK_SHA256: '91310200f072045dc6cef2c8c23e7e6387b37c46e9de49623ce0fa461a24623d'
    steps:
    - name: Checkout the source
      uses: actions/checkout@v2

    - name: Restore boot JDK from cache
      id: bootjdk
      uses: actions/cache@v2
      with:
        path: ~/bootjdk/${{ env.BOOT_JDK_VERSION }}
        key: bootjdk-${{ env.BOOT_JDK_VERSION }}-v3

    - name: Create boot JDK destination folder
      run: mkdir -p ${HOME}/bootjdk/${BOOT_JDK_VERSION}
      if: steps.bootjdk.outputs.cache-hit != 'true'

    - name: Download boot JDK
      run: wget -O "${HOME}/bootjdk/${BOOT_JDK_FILENAME}" "${BOOT_JDK_URL}"
      if: steps.bootjdk.outputs.cache-hit != 'true'

    - name: Verify boot JDK
      run: echo "${BOOT_JDK_SHA256} ${HOME}/bootjdk/${BOOT_JDK_FILENAME}" | sha256sum -c >/dev/null -
      if: steps.bootjdk.outputs.cache-hit != 'true'

    - name: Unpack boot JDK
      run: tar -xf "${HOME}/bootjdk/${BOOT_JDK_FILENAME}" -C "${HOME}/bootjdk/${BOOT_JDK_VERSION}"
      if: steps.bootjdk.outputs.cache-hit != 'true'

    - name: Install dependencies
      run: sudo apt-get install libxrandr-dev libxtst-dev libcups2-dev libasound2-dev

    - name: Configure
      run: bash configure --with-boot-jdk=${HOME}/bootjdk/${BOOT_JDK_VERSION}/jdk-${BOOT_JDK_VERSION}

    - name: Build
      run: make images
      
    - name: Perform a sanity check
      run: ./build/*/images/jdk/bin/java -version

    - name: Create an archive of the build
      run: tar cvz ~/linux_x86_64_release.tar.gz build/

    - name: Persist the build for testing in parallel
      uses: actions/upload-artifact@v2
      with:
        name: linux_x86_64_release
        path: ~/linux_x86_64_release.tar.gz
  
  test_tier1_linux_x86_64_release:
    name: Run tier1 tests for Linux x86_64 Release
    needs: build_linux_x86_64_release
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout the source
        uses: actions/checkout@v2

      - name: Restore boot JDK from cache
        uses: actions/cache@v2
        with:
          path: ~/bootjdk/${{ env.BOOT_JDK_VERSION }}
          key: bootjdk-${{ env.BOOT_JDK_VERSION }}-v3

      - name: Download the persisted build
        uses: actions/download-artifact@v2
        with:
          name: linux_x86_64_release
          path: ~/

      - name: Restore the build folder
        run: tar xfz ~/linux_x86_64_release.tar.gz

      - name: Run tier1 tests
        run: make test-tier1

