name: Build and test

on: [push, pull_request]

jobs:
  linux:
    runs-on: 'ubuntu-latest'
    env: 
      BOOT_JDK_VERSION: '14.0.2'
      BOOT_JDK_FILENAME: openjdk-${{ env.BOOT_JDK_VERSION }}_linux-x64_bin.tar.gz
      BOOT_JDK_URL: https://download.java.net/java/GA/jdk${{ env.BOOT_JDK_VERSION }}/205943a0976c4ed48cb16f1043c5c647/12/GPL/${{ env.BOOT_JDK_FILENAME }}
      BOOT_JDK_SHA256: '91310200f072045dc6cef2c8c23e7e6387b37c46e9de49623ce0fa461a24623d'
      BOOT_JDK_PATH: ${{ env.HOME }}/bootjdk/${BOOT_JDK_VERSION}
    steps:
    - name: Checkout the source
      uses: actions/checkout@v2

#    - name: Restore boot JDK from cache
#      uses: actions/cache@v2

    - name: Create boot JDK destination folder
      run: mkdir -p "${{ env.BOOT_JDK_PATH }}"

    - name: Download boot JDK
      run: wget -O "${{ env.HOME }}/bootjdk/${{ env.BOOT_JDK_FILENAME }}" "${{ env.BOOT_JDK_URL }}"

    - name: Verify boot JDK
      run: echo "${BOOT_JDK_SHA256} ${BOOT_JDK_FILENAME}" | sha256sum -c >/dev/null -

    - name: Unpack boot JDK
      run: tar -xf "${BOOT_JDK_FILENAME}" -C "${BOOT_JDK_PATH}"

    - name: Configure
      run: bash configure --with-boot-jdk=${BOOT_JDK_PATH}
#    - name: Build
#      run: make images
#    - name: Verify
#      run: ./build/*/images/jdk/bin/java -version

