name: Build and test

on: [push, pull_request]

jobs:
  linux:
    runs-on: 'ubuntu-latest'
    env: 
      BOOT_JDK_VERSION: '14.0.2'
      BOOT_JDK_FILENAME: 'openjdk-14.0.2_linux-x64_bin.tar.gz'
      BOOT_JDK_URL: 'https://download.java.net/java/GA/jdk14.0.2/205943a0976c4ed48cb16f1043c5c647/12/GPL/openjdk-14.0.2_linux-x64_bin.tar.gz'
      BOOT_JDK_SHA256: '91310200f072045dc6cef2c8c23e7e6387b37c46e9de49623ce0fa461a24623d'
    steps:
    - name: Checkout the source
      uses: actions/checkout@v2

    - name: Restore boot JDK from cache
      id: bootjdk
      uses: actions/cache@v2
      with:
        path: ${{ env.HOME }}/bootjdk/${{ env.BOOT_JDK_VERSION }}
        key: bootjdk-${{ env.BOOT_JDK_VERSION }}

    - name: Create boot JDK destination folder
      run: mkdir -p ${HOME}/bootjdk/${BOOT_JDK_VERSION}
      if: steps.bootjdk.outcome != success

    - name: Download boot JDK
      run: wget -O "${HOME}/bootjdk/${BOOT_JDK_FILENAME}" "${BOOT_JDK_URL}"
      if: steps.bootjdk.outcome != success

    - name: Verify boot JDK
      run: echo "${BOOT_JDK_SHA256} ${HOME}/bootjdk/${BOOT_JDK_FILENAME}" | sha256sum -c >/dev/null -
      if: steps.bootjdk.outcome != success

    - name: Unpack boot JDK
      run: tar -xf "${HOME}/bootjdk/${BOOT_JDK_FILENAME}" -C "${HOME}/bootjdk/${BOOT_JDK_VERSION}"
      if: steps.bootjdk.outcome != success

    - name: Install dependencies
      run: sudo apt-get install libxrandr-dev libxtst-dev libcups2-dev libasound2-dev

    - name: Configure
      run: bash configure --with-boot-jdk=${HOME}/bootjdk/${BOOT_JDK_VERSION}/jdk-${BOOT_JDK_VERSION}

#    - name: Build
#      run: make images
#    - name: Verify
#      run: ./build/*/images/jdk/bin/java -version

